python3 -m src.main \
    --domain_adversary \
    --early_adversary_supression \
    --matsuura_augmentation \
    --adversarial_examples \
    --save_dir=test_run \
    --gpu=0 \
    --random_seed=16 \
    --adversarial_examples_lr=1e-3 \
    --adversarial_train_steps=1 \
    --adversarial_examples_wd=1e-3 \
    --adversarial_examples_ratio=0.5 \
    --adv_blur_step=4 \
    --adv_kl_weight=1 \
    --single_target=art_painting \
    --use_original_train_set \
    --entropy \
    --num_epochs 1 \
    --verbose